### ISSUE TITLE
application.yml微服务配置

### ISSUE THREAD

**Issue by ZhuangRenyang** [ZhuangRenyang/blog#23]
### application.yml配置
```yml
#指定服务的端口
server:
  port:      #端口号

#公共配置
mybatis:
  configuration:
    #禁用缓存
    cache-enabled: false
    #配置映射驼峰命名法
    map-underscore-to-camel-case: true
    #将运行的sql语句在控制台输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置knife4j
knife4j:
  enable: true #开启增强配置
  production: false #生产环境屏蔽,开启将禁止访问在线API文档
  #Basic认证功能,既是否需要通过用户名, 密码验证后才能访问在线API文档

  basic:
    enable: false #是否开启Basic认证
    #如果开启Basic认证,但是没有配置用户名和密码, 默认是admin/123321
    username: root
    password: root

#指定服务的应用名称(service-id)
spring:
    application:
      name:        #应用名称
    profiles:
      active: dev   #将来会激活dev的profile文件
```

### application-dev.yml配置
```yml
spring:
#配置数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
#配置nacos信息
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #配置sentinel信息
    sentinel:
      transport:
        dashboard: localhost:8080 #配置sentinel仪表盘的位置
        port: 8721 #执行限流的端口，每个项目是唯一的，如果此项目使用了8721端口，其余就不能使用该端口了

#配置dubbo信息
dubbo:
  protocol:
    #port设置成-1是Dubbo框架支持的特殊写法,会自动动态生成可用的端口,规则是从20880开始,
    #如果被占用就递增使用
    port: -1
    #设置连接的名称,一般固定就叫dubbo
    name: dubbo
  registry:
    #声明注册中心的软件类型和ip端口号
    address: nacos://localhost:8848
  consumer:
    #当项目启动时,作为消费者,是否要检查所有远程服务可用,false表示不检查
    check: false

seata:
  tx-service-group: csmall_group  #定义分组名称，一般是为了区分项目
  service:
    vgroup-mapping:
      csmall_group: default   #csmall_group组使用默认的Seata配置完成事务
    grouplist:
      default: localhost:8091 #设置Seata所在的地址，默认端口是8091
```
